# Generated by Django 3.1.7 on 2021-03-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demeter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Nation',
        ),
    ]
